### ISSUE TITLE
Docker and Singularity 

### ISSUE THREAD

**Issue by kayDaramola** [tijeco/FUSTr#1]
Hi there,
I would like to use FUSTr, the challenge is Docker is not allowed on our linux server. I was wondering if there a way to use FUSTr with [Singularity](uhttp://singularity.lbl.gov/index.htmlrl) instead?

thanks
Kay

**Comment by tijeco** [comment]
Hi Kay, FUSTr can still be installed without Docker following the "Installing FUSTr without Docker"
