### ISSUE TITLE
Does FUSTr select only complete ORFs from TransDecoder?

### ISSUE THREAD

**Issue by stupornova33** [tijeco/FUSTr#6]
I.e. ORFs that contain both a start and stop codon?
I couldn't find any information about this in the documentation.

**Comment by tijeco** [comment]
@stupornova33 

Sorry for the delay! I haven't been getting notifications about issues on here for some reason.

I do need to update the documentation, but yes there is a way to only use complete ORFs, but you would have to use the flag `-complete` in your command.

**Comment by stupornova33** [comment]
Thanks for the response! And sorry for the delay in closing the issue.
